# Generated by Django 3.2.4 on 2021-06-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('score', models.PositiveIntegerField(default=0)),
                ('user_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
