# Generated by Django 3.2.4 on 2021-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20210622_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
