# Generated by Django 3.2.4 on 2021-07-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_profile_user_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
